import './style.css';
import './detail.css';
import { lensDetail } from './detail-model.js';
import { renderLensDetails } from './detail-panel.js';
import { DEFAULT_CONFIG, normalizeConfig, solveOptics } from './physics.js';
import { makeTarget, makeProjection } from './projection.js';
import { createProject, parseProject, serializeProject, normalizeView, DEFAULT_VIEW } from './project.js';
import { COMPONENTS } from './geometry.js';
import { LensScene } from './scene.js';

const $ = selector => document.querySelector(selector), $$ = selector => [...document.querySelectorAll(selector)];
const STORAGE_KEY = 'lens-lab-project-v1', desktop = window.lensDesktop;
let config = normalizeConfig(DEFAULT_CONFIG), solution = solveOptics(config), view = normalizeView(DEFAULT_VIEW), comparison = null;
let initialCamera = null, scene, guide = null, previous = null, busy = false, restoring = false, focused = false;
let storageBlocked = false, recoveredRaw = null, saveTimer, toastTimer, pendingDrag = null, dragFrame = null;
let projection, projectionKey, comparedProjection, comparisonKey, projectionMode='current';
const target = makeTarget({ size:192 });
const number = (value, digits=2) => (Math.abs(value) < .5*10**-digits ? 0 : value).toLocaleString('ko-KR',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const text = (selector,value) => { $(selector).textContent = value; };
const same = (a,b) => Object.keys(DEFAULT_CONFIG).every(key => a[key] === b[key]);
const near = (a,b,tolerance=.001) => Math.abs(a-b) <= tolerance;
const kindName = value => ({real:'실상',virtual:'허상',infinity:'무한대'})[value];
function dismissToast() { clearTimeout(toastTimer); $('#toast').hidden=true; }
function toast(message) { const close=Object.assign(document.createElement('button'),{textContent:'닫기',type:'button'}); close.setAttribute('aria-label','알림 닫기'); close.addEventListener('click',dismissToast); $('#toast').replaceChildren(Object.assign(document.createElement('span'),{textContent:message}),close); $('#toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(dismissToast,5000); }
function returnToScene() { dismissToast(); requestAnimationFrame(()=>$('#scene').scrollIntoView({block:'nearest',inline:'nearest'})); }
function capture() { return createProject({config,comparison,view,camera:scene?.getCameraState()??initialCamera}); }
function saveLocal() { clearTimeout(saveTimer); if(storageBlocked||restoring)return; try{localStorage.setItem(STORAGE_KEY,serializeProject(capture()));text('#save-status','이 기기에 자동 저장됨');}catch{text('#save-status','자동 저장을 완료하지 못했습니다 · 파일로 보관하세요');} }
function scheduleSave(){if(!restoring&&!storageBlocked){clearTimeout(saveTimer);saveTimer=setTimeout(saveLocal,230);}}
function protectOriginal(raw,future){recoveredRaw=raw;storageBlocked=true;try{localStorage.setItem(`${STORAGE_KEY}-original-${Date.now()}`,raw);}catch{}$('#storage-recovery').hidden=false;if(future)text('#storage-recovery strong','더 새로운 버전의 실험입니다. 기존 원문을 보존합니다.');text('#save-status','자동 저장 원문 보호 중 · 현재 실험은 파일로 보관하세요');}
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw!==null){try{const saved=parseProject(raw);({config,comparison}=saved);({view,camera:initialCamera}=saved.observation);solution=solveOptics(config);}catch(error){protectOriginal(raw,error.futureVersion);}}}catch{storageBlocked=true;text('#save-status','자동 저장을 사용할 수 없습니다 · 파일로 보관하세요');}

function setBusy(value){busy=value;$('#save-project').disabled=value;$('#open-project').disabled=value;if(desktop?.setBusy)Promise.resolve(desktop.setBusy(value)).catch(()=>{});}
function syncControls(){for(const input of $$('[data-number]'))input.value=config[input.dataset.number];for(const input of $$('[data-range]')){const value=config[input.dataset.range];input.step='any';input.value=value;input.setAttribute('aria-valuetext',`${number(value,9)} mm`);}for(const input of $$('[data-view]'))input.checked=view[input.dataset.view];$('#part-select').value=view.selectedPart;$('#focus-part-select').value=view.selectedPart;$$('[data-lesson]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.lesson===guide?.id)));}
function remember(){flushDrag();previous={project:capture(),guide:structuredClone(guide)};$('#undo-new').hidden=false;}
function readProject(project,restoredGuide=null){const saved=parseProject(serializeProject(project));cancelDrag();restoring=true;try{({config,comparison}=saved);({view,camera:initialCamera}=saved.observation);solution=solveOptics(config);guide=restoredGuide;syncControls();refresh();if(initialCamera)scene?.setCameraState(initialCamera);else scene?.resetCamera();}finally{restoring=false;}saveLocal();}
function newExperiment(){if(busy)return;remember();config=normalizeConfig(DEFAULT_CONFIG);solution=solveOptics(config);comparison=null;guide=null;view=normalizeView(DEFAULT_VIEW);syncControls();refresh();scene?.resetCamera();saveLocal();toast('새 광학 실험입니다. 직전 실험은 되돌릴 수 있습니다.');}
function fixedLessonValues(){if(!guide||guide.status!=='active')return{};if(guide.id==='focus')return{focalLengthMm:150,objectDistanceMm:300,apertureDiameterMm:18};if(guide.id==='image')return{focalLengthMm:150,apertureDiameterMm:18};return guide.stage===0?{focalLengthMm:150,objectDistanceMm:300,screenDistanceMm:320}:{focalLengthMm:150,objectDistanceMm:300,apertureDiameterMm:6};}
function changeConfig(patch,{guided=false}={}){if(busy)return;const next=normalizeConfig({...config,...patch});if(same(config,next))return;if(!guided&&Object.entries(fixedLessonValues()).some(([key,value])=>!near(next[key],value))){guide.status='interrupted';guide.notice='안내의 고정 조건을 바꿨습니다. 지금 조건에서 자유롭게 관찰하거나 안내를 다시 시작하세요.';}config=next;solution=solveOptics(config);syncControls();refresh();scheduleSave();}
function queueDrag(patch){if(busy)return;pendingDrag={...(pendingDrag??{}),...patch};if(dragFrame===null)dragFrame=requestAnimationFrame(()=>{dragFrame=null;const next=pendingDrag;pendingDrag=null;if(next)changeConfig(next);});}
function cancelDrag(){if(dragFrame!==null)cancelAnimationFrame(dragFrame);dragFrame=null;pendingDrag=null;}
function flushDrag(){if(pendingDrag){const next=pendingDrag;cancelDrag();changeConfig(next);}}

const lessons={focus:{title:'거꾸로 맺힌 상에 초점 맞추기',config:{focalLengthMm:150,objectDistanceMm:300,screenDistanceMm:360,apertureDiameterMm:18}},image:{title:'초점을 지나면 상은 어디로?',config:{focalLengthMm:150,objectDistanceMm:300,screenDistanceMm:300,apertureDiameterMm:18}},aperture:{title:'작은 구멍의 대가',config:{focalLengthMm:150,objectDistanceMm:300,screenDistanceMm:320,apertureDiameterMm:18}}};
function startLesson(id){if(busy||!lessons[id])return;remember();config=normalizeConfig(lessons[id].config);solution=solveOptics(config);guide={id,stage:0,status:'active',baseline:structuredClone(config),observed:[]};comparison=id==='aperture'?{label:'조리개 18 mm · 스크린 320 mm',config:structuredClone(config)}:null;view=normalizeView(DEFAULT_VIEW);syncControls();refresh();scene?.resetCamera();scheduleSave();}
function lessonReady(){if(guide?.status!=='active')return false;if(guide.id==='focus')return lensDetail(config,solution).focusTolerance.containsScreen;if(guide.id==='image')return guide.stage===0?near(config.objectDistanceMm,225)&&near(config.screenDistanceMm,450):guide.stage===1?solution.image.kind==='infinity':near(config.objectDistanceMm,100);return guide.stage===0?near(config.apertureDiameterMm,6):near(config.screenDistanceMm,300)&&solution.screen.blurRadiusMm<=.000001;}
function guideNext(){flushDrag();if(!lessonReady())return;guide.observed.push(structuredClone(config));const last=guide.id==='focus'?0:guide.id==='image'?2:1;if(guide.stage===last){guide.status='completed';guide.evidence={baseline:structuredClone(guide.baseline),observed:structuredClone(guide.observed),config:structuredClone(config)};}else guide.stage++;refresh(false);}
function renderGuide(){const panel=$('#lesson-guide');panel.hidden=!guide;$('#guide-next').hidden=!guide||guide.status!=='active';if(!guide)return;text('#guide-title',lessons[guide.id].title);text('#guide-progress',guide.status==='completed'?'관찰 완료':guide.status==='interrupted'?'직접 조절 중':`관찰 ${guide.stage+1} / ${guide.id==='focus'?1:guide.id==='image'?3:2}`);let action='',result='';
  if(guide.status==='interrupted')action=guide.notice;
  else if(guide.status==='completed'){action='완료 시점의 결과를 보관했습니다. 현재 계측값은 이후 조절한 조건을 보여 줍니다.';const evidence=guide.evidence,end=solveOptics(evidence.config);if(guide.id==='focus')result=`스크린 ${number(evidence.config.screenDistanceMm,1)} mm에서 점 흐림 ${number(end.screen.blurRadiusMm,3)} mm. 예상 상은 300 mm의 거꾸로 선 1배 실상입니다.`;else if(guide.id==='image')result='물체 225 mm → 실상 450 mm, −2배\n물체 150 mm → 유한한 초점 없음\n물체 100 mm → 허상 −300 mm, +3배';else{const before=solveOptics(evidence.baseline),small=solveOptics(evidence.observed[0]);result=`조리개 18 → 6 mm: 흐림 ${number(before.screen.blurRadiusMm,2)} → ${number(small.screen.blurRadiusMm,2)} mm, 포집 광량 ${number(before.light.collectedRelative,3)} → ${number(small.light.collectedRelative,3)}. 초점은 조리개 크기와 관계없이 300 mm입니다.`;}}
  else if(guide.id==='focus')action='스크린을 움직여 점 흐림 반지름을 0.10 mm 이하로 줄이세요. 문양의 방향과 크기를 확인한 뒤 관찰 확인을 누릅니다. 0.10 mm는 이 안내의 판정 기준입니다.';
  else if(guide.id==='image')action=['물체 거리를 225 mm, 스크린 거리를 450 mm로 옮기세요. 300 mm에서 보던 상과 방향·크기를 비교합니다.','물체 거리를 초점거리인 150 mm로 옮기세요. 한 물체점의 출사 광선이 평행해지고 유한한 스크린 초점이 사라집니다.','물체 거리를 100 mm로 옮기세요. 왼쪽의 허상 위치는 역연장 표시입니다. 실제 스크린에 선명한 허상이 맺히는지 구분하세요.'][guide.stage];
  else action=guide.stage===0?'18 mm의 흐린 영상과 광량을 비교 기준으로 보관했습니다. 스크린 320 mm에서 조리개를 6 mm로 줄이고 변화를 확인하세요.':'조리개 6 mm를 유지하고 스크린을 300 mm로 옮기세요. 기하학적 초점 위치가 구경에 따라 변하는지 확인합니다. 실제 렌즈의 회절은 이번 모형에 포함하지 않습니다.';
  text('#guide-action',action);text('#guide-result',result);$('#guide-next').disabled=!lessonReady();text('#guide-next',lessonReady()?'관찰 확인 · 다음으로':'조건을 맞춘 뒤 관찰 확인');
}
function drawRaster(selector,raster){const canvas=$(selector);if(canvas.width!==raster.width)canvas.width=raster.width;if(canvas.height!==raster.height)canvas.height=raster.height;canvas.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(raster.rgba),raster.width,raster.height),0,0);}
function renderProjectionMode(){if(!comparison)projectionMode='current';const saved=projectionMode==='saved';$('#projection-tabs').hidden=!comparison;$('#screen-preview').hidden=saved;$('#comparison-preview').hidden=!saved;$('#show-current').setAttribute('aria-pressed',String(!saved));$('#show-saved').setAttribute('aria-pressed',String(saved));text('#projection-state',saved?'보관한 조건 · 계측값은 현재 조건':'현재 조건');}
function refresh(renderScene=true){const key=JSON.stringify(config);if(key!==projectionKey){projection=makeProjection(solution,{size:192});projectionKey=key;projectionMode='current';drawRaster('#screen-preview',projection);drawRaster('#control-preview',projection);}if(renderScene&&scene)scene.update(solution,view,{projection,target});
  text('#image-kind',kindName(solution.image.kind));text('#image-orientation',solution.image.kind==='real'?'거꾸로 선 상':solution.image.kind==='virtual'?'바로 선 상 · 역연장으로 관찰':'한 물체점의 출사 광선이 평행');
  const distance=solution.image.distanceMm;text('#image-distance',distance===null?'∞':`${Math.abs(distance)>=100000?distance.toExponential(2):number(distance,1)} mm`);text('#image-location',distance===null?'유한한 거리의 초점 없음':solution.image.kind==='virtual'?'물체 쪽 · 스크린에 맺히지 않음':solution.image.onBench?'스크린 쪽 · 레일 안':'스크린 쪽 · 레일 범위 밖');
  text('#magnification',solution.image.magnification===null?'정의되지 않음':`${Math.abs(solution.image.magnification)>10000?solution.image.magnification.toExponential(2):number(solution.image.magnification,2)} 배`);text('#blur-radius',`${number(solution.screen.blurRadiusMm,3)} mm`);text('#collected-light',`${number(solution.light.collectedRelative,3)} ×`);
  text('#screen-explanation',solution.image.kind==='virtual'?'허상은 실제 스크린의 선명한 투영이 아닙니다. 여기에는 현재 광선이 스크린에 만든 퍼진 빛을 표시합니다.':solution.image.kind==='infinity'?'물체가 초점에 있습니다. 스크린을 유한한 거리로 옮겨도 한 점으로 모이지 않습니다.':lensDetail(config,solution).focusTolerance.containsScreen?'기하학적 초점 근처입니다. 원래 물체와 문양의 방향·크기를 비교하세요.':'스크린이 예상 상의 위치에서 벗어나 빛이 퍼집니다. 스크린을 이동해 문양의 변화를 관찰하세요.');
  text('#scene-status',view.structure?'렌즈 중심의 모델 평면 · 구조 표현의 유리 두께는 계산에서 제외':'물체·스크린 캐리지를 끌어 이동 · 나머지 공간을 끌어 시점 회전');
  const part=COMPONENTS.find(item=>item.id===view.selectedPart);if(part){text('#part-name',part.name);text('#part-material',part.material);text('#part-description',part.description);}
  renderLensDetails(config,solution,view,lensDetail(config,solution));
  text('#control-readout',`점 흐림 ${number(solution.screen.blurRadiusMm,3)} mm\n상대 광량 ${number(solution.light.collectedRelative,3)} ×`);
  $('#comparison').hidden=!comparison;if(comparison){const old=solveOptics(comparison.config),comparedKey=JSON.stringify(comparison.config);if(comparedKey!==comparisonKey){comparedProjection=makeProjection(old,{size:192});comparisonKey=comparedKey;drawRaster('#comparison-preview',comparedProjection);}text('#comparison-summary',`${comparison.label}\n흐림 ${number(old.screen.blurRadiusMm,3)} mm\n상대 광량 ${number(old.light.collectedRelative,3)} ×\n${kindName(old.image.kind)}`);}renderProjectionMode();renderGuide();
}
function pinComparison(){flushDrag();comparison={label:`물체 ${number(config.objectDistanceMm,1)} · 스크린 ${number(config.screenDistanceMm,1)} mm`,config:structuredClone(config)};refresh(false);scheduleSave();}
function browserDownload(contents,name,mime='application/json;charset=utf-8'){const url=URL.createObjectURL(new Blob([contents],{type:mime}));const link=Object.assign(document.createElement('a'),{href:url,download:name});link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function saveFile(){if(busy)return;flushDrag();setBusy(true);try{const contents=serializeProject(capture()),name=`lens-lab-${new Date().toISOString().slice(0,10)}.json`;if(desktop){const result=await desktop.saveProject({contents,name});if(result.canceled){toast('저장을 취소했습니다. 현재 실험은 유지합니다.');return;}}else browserDownload(contents,name);saveLocal();toast('실험 조건·비교 기준·관찰 시점을 저장했습니다.');}catch(error){toast(`저장하지 못했습니다. ${error.message}`);}finally{setBusy(false);}}
async function openFile(){if(busy)return;flushDrag();if(!desktop){$('#project-file').click();return;}setBusy(true);try{const result=await desktop.openProject();if(result.canceled){toast('열기를 취소했습니다. 현재 실험은 유지합니다.');return;}const saved=parseProject(result.content);remember();readProject(saved);toast('저장한 광학 실험을 복원했습니다.');}catch(error){toast(`열지 못했습니다. ${error.message}`);}finally{setBusy(false);}}
function toggleFocus(){focused=!focused;document.body.classList.toggle('focus-mode',focused);text('#focus',focused?'실험 화면으로':'3D 크게 보기');returnToScene();}

$('#part-select').replaceChildren(...COMPONENTS.map(part=>Object.assign(document.createElement('option'),{value:part.id,textContent:part.name})));
$('#focus-part-select').replaceChildren(...COMPONENTS.map(part=>Object.assign(document.createElement('option'),{value:part.id,textContent:part.name})));
$$('[data-number]').forEach(input=>{if(input.type==='number')input.step='any';});drawRaster('#target-preview',target);
try{scene=new LensScene($('#scene'),{onConfigChange:queueDrag,onSelect:id=>{view.selectedPart=id;syncControls();refresh();scheduleSave();},onCameraChange:scheduleSave});if(initialCamera)scene.setCameraState(initialCamera);}catch(error){$('#scene-error').hidden=false;text('#scene-error',`3D 화면을 시작하지 못했습니다. ${error.message}`);}
syncControls();refresh();if(!initialCamera)scene?.resetCamera();
$('#settings-form').addEventListener('submit',event=>{event.preventDefault();if(busy||!event.currentTarget.reportValidity())return;const patch=Object.fromEntries($$('[data-number]').map(input=>[input.dataset.number,Number(input.value)]));flushDrag();changeConfig(patch);});
$$('[data-number]').forEach(input=>input.addEventListener('change',()=>{if(input.reportValidity()){const patch={[input.dataset.number]:Number(input.value)};flushDrag();changeConfig(patch);}}));
$$('[data-range]').forEach(input=>input.addEventListener('input',()=>queueDrag({[input.dataset.range]:Number(input.value)})));
$$('[data-range]').forEach(input=>input.addEventListener('keydown',event=>{const directions={ArrowLeft:-1,ArrowDown:-1,ArrowRight:1,ArrowUp:1,PageDown:-10,PageUp:10};if(!(event.key in directions)&&event.key!=='Home'&&event.key!=='End')return;event.preventDefault();const key=input.dataset.range,increment=(key==='apertureDiameterMm'?.1:1)*(event.shiftKey?.1:1),current=pendingDrag?.[key]??config[key];const value=event.key==='Home'?Number(input.min):event.key==='End'?Number(input.max):Math.min(Number(input.max),Math.max(Number(input.min),current+directions[event.key]*increment));queueDrag({[key]:value});}));
$$('[data-view]').forEach(input=>input.addEventListener('change',()=>{view[input.dataset.view]=input.checked;refresh();scheduleSave();}));
$$('[data-camera]').forEach(button=>button.addEventListener('click',()=>{scene?.resetCamera(button.dataset.camera);returnToScene();}));
for(const selector of ['#part-select','#focus-part-select'])$(selector).addEventListener('change',event=>{view.selectedPart=event.target.value;syncControls();refresh();scheduleSave();});for(const selector of ['#focus-part','#focus-part-inline'])$(selector).addEventListener('click',()=>{scene?.focusPart(view.selectedPart);returnToScene();});$('#focus').addEventListener('click',toggleFocus);
$$('[data-lesson]').forEach(button=>button.addEventListener('click',()=>startLesson(button.dataset.lesson)));$('#guide-next').addEventListener('click',guideNext);$('#guide-restart').addEventListener('click',()=>{if(guide)startLesson(guide.id);});$('#guide-exit').addEventListener('click',()=>{guide=null;syncControls();refresh(false);});
$('#pin-comparison').addEventListener('click',pinComparison);$('#clear-comparison').addEventListener('click',()=>{comparison=null;refresh(false);scheduleSave();});$('#new-project').addEventListener('click',newExperiment);
$('#show-current').addEventListener('click',()=>{projectionMode='current';renderProjectionMode();});$('#show-saved').addEventListener('click',()=>{if(comparison){projectionMode='saved';renderProjectionMode();}});$('#show-observation').addEventListener('click',()=>{$('.observation').scrollIntoView({block:'start'});});
$('#undo-new').addEventListener('click',()=>{if(!previous||busy)return;const saved=previous;previous=null;readProject(saved.project,saved.guide);$('#undo-new').hidden=true;toast('직전 실험과 안내를 복원했습니다.');});
$('#save-project').addEventListener('click',saveFile);$('#open-project').addEventListener('click',openFile);$('#project-file').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file||busy)return;flushDrag();setBusy(true);try{if(file.size>10*1024*1024)throw new Error('실험 파일은 10 MiB 이하여야 합니다.');const saved=parseProject(await file.text());remember();readProject(saved);toast('저장한 광학 실험을 복원했습니다.');}catch(error){toast(`열지 못했습니다. ${error.message}`);}finally{event.target.value='';setBusy(false);}});
$('#recover-original').addEventListener('click',()=>{if(recoveredRaw!==null)browserDownload(recoveredRaw,'lens-lab-original.txt','text/plain;charset=utf-8');});$('#close-help').addEventListener('click',()=>$('#help-dialog').close());
desktop?.onCommand(command=>{if(busy)return;if(command==='new-project')newExperiment();else if(command==='open-project')openFile();else if(command==='save-project')saveFile();else if(command==='toggle-rays'){view.rays=!view.rays;syncControls();refresh();scheduleSave();}else if(command==='focus')toggleFocus();else if(command==='help')$('#help-dialog').showModal();});
window.addEventListener('beforeunload',()=>{flushDrag();saveLocal();});document.addEventListener('visibilitychange',()=>{if(document.hidden){flushDrag();saveLocal();}});
window.lensLab={getState:()=>structuredClone({config,solution,view,comparison,detail:lensDetail(config,solution),focused}),project:()=>structuredClone(capture()),loadProject:raw=>{const saved=parseProject(raw);readProject(saved);return structuredClone(capture());},sceneDebug:()=>scene?.getDebug()??null,guide:()=>structuredClone(guide),components:()=>COMPONENTS.map(part=>({...part}))};
window.render_game_to_text=()=>JSON.stringify({...window.lensLab.getState(),coordinates:'Optical lengths in mm, 3D in m; lens x=0, optical axis +X, target -X, screen +X, vertical +Y.'});
window.advanceTime=()=>{flushDrag();scene?.render();return window.render_game_to_text();};
